//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalExam.Models
{
    using System;
    using System.Collections.Generic;

     public partial class Team
     {
         public int TeamID { get; set; }
         public string Name { get; set; }
         public Nullable<int> Games { get; set; }
         public Nullable<int> Wins { get; set; }
         public Nullable<int> Losses { get; set; }
         public Nullable<int> OvertimeLosses { get; set; }
         public Nullable<int> Points { get; set; }
         public int DivisionID { get; set; }
         public string Logo { get; set; }

         public virtual Division Division { get; set; }
     }
}